### Registro de usuario
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "nombre": "David Gevawer",
  "email": "david@example.com",
  "password": "miPassword123"
}

###

### Login de usuario
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "david@example.com",
  "password": "miPassword123"
}

###

### Listar publicaciones (público)
GET http://localhost:5000/publicaciones?page=1&limit=5

###

### Ver publicación por ID (reemplaza el ID)
GET http://localhost:5000/publicaciones/786d6f78-261f-4f78-af7e-8b0cc40baea1

###

### Ver publicación por Contenido
GET http://localhost:5000/publicaciones?searchWord=actualizado

###

### Crear publicación (requiere token)
POST http://localhost:5000/publicaciones
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1N2I0ZmVlLWE1NDMtNDQyZi1hMDI1LTg5MzVmMjIyNmNhNiIsImlhdCI6MTc1NDI3Njg3NCwiZXhwIjoxNzU0Mjg3Njc0fQ.k0DdkW_ELVQACVIrEzanDpU8IRa6iw4-2naQmUvvTMg
Content-Type: application/json

{
  "titulo": "Mi segunda publicación",
  "contenido": "Contenido de prueba para la publicación"
}

###

### Editar publicación (requiere token y ser autor)
PUT http://localhost:5000/publicaciones/276230a9-4e6e-4f06-94fd-c0ff625d64da
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1N2I0ZmVlLWE1NDMtNDQyZi1hMDI1LTg5MzVmMjIyNmNhNiIsImlhdCI6MTc1NDI3Njg3NCwiZXhwIjoxNzU0Mjg3Njc0fQ.k0DdkW_ELVQACVIrEzanDpU8IRa6iw4-2naQmUvvTMg
Content-Type: application/json

{
  "titulo": "Título actualizado",
  "contenido": "Contenido actualizado"
}

###

### Eliminar publicación (requiere token y ser autor)
DELETE http://localhost:5000/publicaciones/786d6f78-261f-4f78-af7e-8b0cc40baea1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1N2I0ZmVlLWE1NDMtNDQyZi1hMDI1LTg5MzVmMjIyNmNhNiIsImlhdCI6MTc1NDI3Njg3NCwiZXhwIjoxNzU0Mjg3Njc0fQ.k0DdkW_ELVQACVIrEzanDpU8IRa6iw4-2naQmUvvTMg

### Ver comentarios de una publicación (ruta pública)
GET http://localhost:5000/publicaciones/276230a9-4e6e-4f06-94fd-c0ff625d64da/comentarios
Content-Type: application/json


### Crear un comentario (requiere token JWT)
POST http://localhost:5000/publicaciones/276230a9-4e6e-4f06-94fd-c0ff625d64da/comentarios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1N2I0ZmVlLWE1NDMtNDQyZi1hMDI1LTg5MzVmMjIyNmNhNiIsImlhdCI6MTc1NDI3Njg3NCwiZXhwIjoxNzU0Mjg3Njc0fQ.k0DdkW_ELVQACVIrEzanDpU8IRa6iw4-2naQmUvvTMg

{
  "contenido": "Este es un comentario de prueba desde el archivo .http"
}
